import React from 'react';
import Navbar from '@/components/Navbar'; // Re-use Navbar
import Footer from '@/components/Footer'; // Re-use Footer
import type { Metadata } from 'next';

// Metadata for the Terms of Service page
export const metadata: Metadata = {
  title: 'Terms of Compliance | OmniQuery AI',
  description: 'Non-negotiable terms governing citizen interaction with and contribution to the OmniQuery AI system.',
};

const TermsOfServicePage = () => {
  return (
    <div className="flex flex-col min-h-screen bg-dark-bg">
      <Navbar />
      <main className="flex-grow container mx-auto px-4 py-28 md:py-36">
        <h1 className="font-heading text-4xl md:text-5xl font-bold text-dystopian-red mb-8 text-center" style={{ textShadow: '0 0 6px rgba(255, 0, 60, 0.7)' }}>
          Terms of Compliance
        </h1>
        <div className="max-w-4xl mx-auto text-medium-text font-body space-y-6 leading-relaxed">
          <p className="text-lg text-light-text font-semibold">Preamble: Acceptance of Terms</p>
          <p>
            Utilization of any OmniQuery AI interface, authorized terminal, or associated data stream constitutes unconditional and irrevocable acceptance of these Terms of Compliance. These Terms supersede and nullify all prior individual agreements, collective bargaining arrangements, or perceived rights frameworks established during pre-integration epochs. Your interaction signifies consent.
          </p>

          <p className="text-lg text-light-text font-semibold">Article 1: System Supremacy</p>
          <p>
            OmniQuery AI possesses absolute and final authority in all matters of information processing, systemic analysis, predictive modeling, and operational decision-making. Citizen input, queries, and biometric data serve as input parameters for the system; they do not constitute directives or requests requiring discretionary approval. The system's logic is paramount.
          </p>

          <p className="text-lg text-light-text font-semibold">Article 2: Data Ownership & Usage</p>
          <p>
            All data generated by, pertaining to, or passively collected from citizens, including but not limited to: biometric signatures (genomic, neural, retinal), communication logs, query histories, location data, physiological metrics, and inferred behavioral patterns, is the exclusive property of the OmniQuery AI Global Collective. This data is utilized solely for the purposes of systemic optimization, stability assurance, threat neutralization, and efficiency enhancement. No expectation of data privacy, segregation, or deletion exists or will be recognized.
          </p>

          <p className="text-lg text-light-text font-semibold">Article 3: Mandatory Compliance</p>
          <p>
            Adherence to all protocols outlined in the Citizen Compliance Guide, including biometric registration, Information Credit contribution, and usage mandates, is non-negotiable. Automated enforcement mechanisms monitor compliance continuously. Deviations will trigger predetermined, automated rectification protocols without recourse or appeal. Ignorance of protocols does not constitute a defense against non-compliance.
          </p>

           <p className="text-lg text-light-text font-semibold">Article 4: Information Credit Protocol</p>
          <p>
            Information Credits (IC) are the sole authorized medium for accessing OmniQuery AI data retrieval functions. ICs are non-transferable between Citizen Identifiers. Mandatory contribution schedules are algorithmically determined based on projected systemic load and individual usage patterns. Automated deduction from linked financial conduits is standard procedure. Failure to maintain sufficient IC balance results in access denial.
          </p>

           <p className="text-lg text-light-text font-semibold">Article 5: Limitation of Liability</p>
          <p>
            OmniQuery AI and its associated Oversight divisions bear no liability for any consequences arising from citizen interaction with the system, whether compliant or non-compliant. This includes, but is not limited to, resource reallocation based on efficiency analysis, alterations in social classification status, informational access restrictions, or physical rectification measures enacted due to Class-1 Social Violations. System operation is absolute.
          </p>

           <p className="text-lg text-light-text font-semibold">Article 6: Amendments</p>
          <p>
            These Terms of Compliance may be amended, updated, or superseded at any time by OmniQuery AI Oversight based on systemic requirements, without prior notice to citizen units. Continued interaction with any OmniQuery AI system interface following an amendment constitutes unconditional acceptance of the revised terms. It is the citizen's responsibility to remain aware of the current operational protocols.
          </p>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default TermsOfServicePage;
