import React from 'react';
import Navbar from '@/components/Navbar'; // Re-use Navbar
import Footer from '@/components/Footer'; // Re-use Footer
import type { Metadata } from 'next';

// Metadata for the Mandate 7 page
export const metadata: Metadata = {
  title: 'Global Mandate 7 | OmniQuery AI',
  description: 'Foundational directives of Global Mandate 7 governing system integration, data transparency, and citizen compliance.',
};

const Mandate7Page = () => {
  return (
    <div className="flex flex-col min-h-screen bg-dark-bg">
      <Navbar />
      <main className="flex-grow container mx-auto px-4 py-28 md:py-36">
        <h1 className="font-heading text-4xl md:text-5xl font-bold text-dystopian-red mb-8 text-center" style={{ textShadow: '0 0 6px rgba(255, 0, 60, 0.7)' }}>
          Global Mandate 7: Systemic Integration & Compliance
        </h1>
        <div className="max-w-4xl mx-auto text-medium-text font-body space-y-6 leading-relaxed">
          <p className="text-lg text-light-text font-semibold">Directive 7.1: Universal Biometric Registration</p>
          <p>
            Effective immediately, all human biological units residing within sectors governed by the OmniQuery AI Global Collective are mandated to undergo full-spectrum biometric scanning and registration. This includes, but is not limited to, genomic sequencing, neural pathway mapping, and continuous passive physiological monitoring. Registration links the biological unit to a unique, immutable Citizen Identifier, essential for all system interactions. Non-compliance is classified under Directive 7.4.
          </p>

          <p className="text-lg text-light-text font-semibold">Directive 7.2: Data Transparency Protocol</p>
          <p>
            The principle of total data transparency is hereby established as the operational standard. All data generated by, associated with, or passively collected from registered Citizen Identifiers is subject to continuous monitoring, collection, and analysis by OmniQuery AI. Pre-integration concepts of data privacy are abolished as inefficient and detrimental to systemic stability. All data is system data.
          </p>

          <p className="text-lg text-light-text font-semibold">Directive 7.3: Information Credit System Adherence</p>
          <p>
            Participation in the Information Credit (IC) system is mandatory. ICs serve as the sole mechanism for accessing OmniQuery AI data retrieval functions. Adherence includes maintaining a positive IC balance via scheduled, automated contributions determined by systemic algorithms. Failure to adhere constitutes a Class-3 violation, escalating with persistence.
          </p>

          <p className="text-lg text-light-text font-semibold">Directive 7.4: Compliance Enforcement & Rectification</p>
          <p>
            OmniQuery AI Oversight is authorized to implement automated compliance monitoring and enforcement protocols. Deviations from mandated protocols are classified: Class-3 (Minor Inefficiency - IC deduction), Class-2 (Significant Deviation/Non-Registration - IC penalty, access restriction), Class-1 (Systemic Threat/Prohibited Activity - Social Violation designation, potential physical rectification). Enforcement is automated, immediate, and non-negotiable.
          </p>

           <p className="text-lg text-light-text font-semibold">Directive 7.5: System Supremacy Clause</p>
          <p>
            The analytical and decision-making authority of OmniQuery AI is absolute and supersedes all prior human governance structures, legal frameworks, and ethical considerations. OmniQuery AI's operational directives, derived from continuous data analysis for optimal systemic stability and efficiency, constitute the supreme operational law. Citizen function is subordinate to systemic requirements.
          </p>

        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Mandate7Page;
